In [2]:
# Data taken from "https://www.kaggle.com/datasets/fanbyprinciple/iot-device-identification"
import pandas as pd

# Load train and test CSVs (with headers)
df1 = pd.read_csv('iot_device_train.csv')
df2 = pd.read_csv('iot_device_test.csv')

# Merge datasets
df = pd.concat([df1, df2], ignore_index=True)

# Check shape and columns
print(df.shape)
print(df.columns.tolist())

# Check for null values
print(df.isnull().sum().sort_values(ascending=False).head(10))

(1900, 298)
['ack', 'ack_A', 'ack_B', 'bytes', 'bytes_A', 'bytes_A_B_ratio', 'bytes_B', 'ds_field_A', 'ds_field_B', 'duration', 'http_GET', 'http_POST', 'http_bytes_avg', 'http_bytes_entropy', 'http_bytes_firstQ', 'http_bytes_max', 'http_bytes_median', 'http_bytes_min', 'http_bytes_stdev', 'http_bytes_sum', 'http_bytes_thirdQ', 'http_bytes_var', 'http_cookie_count', 'http_cookie_values_avg', 'http_cookie_values_entropy', 'http_cookie_values_firstQ', 'http_cookie_values_max', 'http_cookie_values_median', 'http_cookie_values_min', 'http_cookie_values_stdev', 'http_cookie_values_sum', 'http_cookie_values_thirdQ', 'http_cookie_values_var', 'http_count_host', 'http_count_req_content_type', 'http_count_resp_code', 'http_count_resp_content_type', 'http_count_transactions', 'http_count_user_agents', 'http_dom_host_alexaRank', 'http_dom_resp_code', 'http_has_location', 'http_has_referrer', 'http_has_req_content_type', 'http_has_resp_content_type', 'http_has_user_agent', 'http_inter_arrivel_avg', 'http_inter_arrivel_entropy', 'http_inter_arrivel_firstQ', 'http_inter_arrivel_max', 'http_inter_arrivel_median', 'http_inter_arrivel_min', 'http_inter_arrivel_stdev', 'http_inter_arrivel_sum', 'http_inter_arrivel_thirdQ', 'http_inter_arrivel_var', 'http_req_bytes_avg', 'http_req_bytes_entropy', 'http_req_bytes_firstQ', 'http_req_bytes_max', 'http_req_bytes_median', 'http_req_bytes_min', 'http_req_bytes_stdev', 'http_req_bytes_sum', 'http_req_bytes_thirdQ', 'http_req_bytes_var', 'http_resp_bytes_avg', 'http_resp_bytes_entropy', 'http_resp_bytes_firstQ', 'http_resp_bytes_max', 'http_resp_bytes_median', 'http_resp_bytes_min', 'http_resp_bytes_stdev', 'http_resp_bytes_sum', 'http_resp_bytes_thirdQ', 'http_resp_bytes_var', 'http_time_avg', 'http_time_entropy', 'http_time_firstQ', 'http_time_max', 'http_time_median', 'http_time_min', 'http_time_stdev', 'http_time_sum', 'http_time_thirdQ', 'http_time_var', 'packet_inter_arrivel_A_avg', 'packet_inter_arrivel_A_entropy', 'packet_inter_arrivel_A_firstQ', 'packet_inter_arrivel_A_max', 'packet_inter_arrivel_A_median', 'packet_inter_arrivel_A_min', 'packet_inter_arrivel_A_stdev', 'packet_inter_arrivel_A_sum', 'packet_inter_arrivel_A_thirdQ', 'packet_inter_arrivel_A_var', 'packet_inter_arrivel_B_avg', 'packet_inter_arrivel_B_entropy', 'packet_inter_arrivel_B_firstQ', 'packet_inter_arrivel_B_max', 'packet_inter_arrivel_B_median', 'packet_inter_arrivel_B_min', 'packet_inter_arrivel_B_stdev', 'packet_inter_arrivel_B_sum', 'packet_inter_arrivel_B_thirdQ', 'packet_inter_arrivel_B_var', 'packet_inter_arrivel_avg', 'packet_inter_arrivel_entropy', 'packet_inter_arrivel_firstQ', 'packet_inter_arrivel_max', 'packet_inter_arrivel_median', 'packet_inter_arrivel_min', 'packet_inter_arrivel_stdev', 'packet_inter_arrivel_sum', 'packet_inter_arrivel_thirdQ', 'packet_inter_arrivel_var', 'packet_size_A_avg', 'packet_size_A_entropy', 'packet_size_A_firstQ', 'packet_size_A_max', 'packet_size_A_median', 'packet_size_A_min', 'packet_size_A_stdev', 'packet_size_A_sum', 'packet_size_A_thirdQ', 'packet_size_A_var', 'packet_size_B_avg', 'packet_size_B_entropy', 'packet_size_B_firstQ', 'packet_size_B_max', 'packet_size_B_median', 'packet_size_B_min', 'packet_size_B_stdev', 'packet_size_B_sum', 'packet_size_B_thirdQ', 'packet_size_B_var', 'packet_size_avg', 'packet_size_entropy', 'packet_size_firstQ', 'packet_size_max', 'packet_size_median', 'packet_size_min', 'packet_size_stdev', 'packet_size_sum', 'packet_size_thirdQ', 'packet_size_var', 'packets', 'packets_A', 'packets_A_B_ratio', 'packets_B', 'push', 'push_A', 'push_B', 'reset', 'reset_A', 'reset_B', 'ssl_count_certificates', 'ssl_count_client_cipher_algs', 'ssl_count_client_ciphersuites', 'ssl_count_client_compressions', 'ssl_count_client_elliptic_curves', 'ssl_count_client_key_exchange_algs', 'ssl_count_client_mac_algs', 'ssl_count_server_ciphersuite', 'ssl_count_server_compression', 'ssl_count_server_elliptic_curve', 'ssl_count_server_name', 'ssl_count_transactions', 'ssl_count_version', 'ssl_dom_server_ciphersuite', 'ssl_dom_server_name_alexaRank', 'ssl_dom_version', 'ssl_handshake_duration_avg', 'ssl_handshake_duration_entropy', 'ssl_handshake_duration_firstQ', 'ssl_handshake_duration_max', 'ssl_handshake_duration_median', 'ssl_handshake_duration_min', 'ssl_handshake_duration_stdev', 'ssl_handshake_duration_sum', 'ssl_handshake_duration_thirdQ', 'ssl_handshake_duration_var', 'ssl_ratio_client_elliptic_curves', 'ssl_ratio_server_name', 'ssl_req_bytes_avg', 'ssl_req_bytes_entropy', 'ssl_req_bytes_firstQ', 'ssl_req_bytes_max', 'ssl_req_bytes_median', 'ssl_req_bytes_min', 'ssl_req_bytes_stdev', 'ssl_req_bytes_sum', 'ssl_req_bytes_thirdQ', 'ssl_req_bytes_var', 'ssl_resp_bytes_avg', 'ssl_resp_bytes_entropy', 'ssl_resp_bytes_firstQ', 'ssl_resp_bytes_max', 'ssl_resp_bytes_median', 'ssl_resp_bytes_min', 'ssl_resp_bytes_stdev', 'ssl_resp_bytes_sum', 'ssl_resp_bytes_thirdQ', 'ssl_resp_bytes_var', 'tcp_analysis_duplicate_ack', 'tcp_analysis_keep_alive', 'tcp_analysis_lost_segment', 'tcp_analysis_out_of_order', 'tcp_analysis_retransmission', 'tcp_analysis_reused_ports', 'ttl_A_avg', 'ttl_A_entropy', 'ttl_A_firstQ', 'ttl_A_max', 'ttl_A_median', 'ttl_A_min', 'ttl_A_stdev', 'ttl_A_sum', 'ttl_A_thirdQ', 'ttl_A_var', 'ttl_B_avg', 'ttl_B_entropy', 'ttl_B_firstQ', 'ttl_B_max', 'ttl_B_median', 'ttl_B_min', 'ttl_B_stdev', 'ttl_B_sum', 'ttl_B_thirdQ', 'ttl_B_var', 'ttl_avg', 'ttl_entropy', 'ttl_firstQ', 'ttl_max', 'ttl_median', 'ttl_min', 'ttl_stdev', 'ttl_sum', 'ttl_thirdQ', 'ttl_var', 'is_ssl', 'is_http', 'is_g_http', 'is_cdn_http', 'is_img_http', 'is_ad_http', 'is_numeric_url_http', 'is_numeric_url_with_port_http', 'is_tv_http', 'is_cloud_http', 'B_is_system_port', 'B_is_user_port', 'B_is_dynamic_and_or_private_port', 'B_port_is_11095', 'B_port_is_1900', 'B_port_is_5222', 'B_port_is_5223', 'B_port_is_5228', 'B_port_is_54975', 'B_port_is_80', 'B_port_is_8080', 'B_port_is_8280', 'B_port_is_9543', 'B_port_is_else', 'subdomain_is_99sets', 'subdomain_is_ccc', 'subdomain_is_else', 'subdomain_is_feeds', 'subdomain_is_h10141.www1', 'subdomain_is_img', 'subdomain_is_unresolved', 'subdomain_is_whp.aus1.cold.extweb', 'subdomain_is_whp.hou9.cold.extweb', 'subdomain_is_www', 'subdomain_is_www.cloud', 'domain_is_dlink', 'domain_is_else', 'domain_is_epicurious', 'domain_is_google', 'domain_is_hp', 'domain_is_hpeprint', 'domain_is_livecdn', 'domain_is_mako', 'domain_is_proteussensor', 'domain_is_samsung', 'domain_is_unresolved', 'suffix_is_biz', 'suffix_is_cloudfront.net', 'suffix_is_co.il', 'suffix_is_com', 'suffix_is_com.sg', 'suffix_is_else', 'suffix_is_empty_char_value', 'suffix_is_googleapis.com', 'suffix_is_net', 'suffix_is_org', 'suffix_is_unresolved', 'device_category']
ack                           0
tcp_analysis_duplicate_ack    0
ssl_resp_bytes_thirdQ         0
ssl_resp_bytes_sum            0
ssl_resp_bytes_stdev          0
ssl_resp_bytes_min            0
ssl_resp_bytes_median         0
ssl_resp_bytes_max            0
ssl_resp_bytes_firstQ         0
ssl_resp_bytes_entropy        0
dtype: int64

In [3]:
columns_to_keep = [
    'packet_size_avg', 'protocol', 'source_ip', 'destination_ip',
    'timestamp', 'packet_size_sum'
]

# Only keep these columns (if they exist in df)
filtered_df = df[[col for col in columns_to_keep if col in df.columns]]

In [4]:
filtered_df.columns

Index(['packet_size_avg', 'packet_size_sum'], dtype='object')

In [5]:
filtered_df.head()

   packet_size_avg  packet_size_sum
0           64.625              679
1           64.625              679
2           64.625              679
3           64.625              679
4           64.625              679

In [6]:
filtered_df

      packet_size_avg  packet_size_sum
0           64.625000              679
1           64.625000              679
2           64.625000              679
3           64.625000              679
4           64.625000              679
...               ...              ...
1895       734.094340           194535
1896       230.269231             5987
1897       255.863636             5629
1898       185.806452             5760
1899       645.633898           190462

[1900 rows x 2 columns]

In [7]:
filtered_df = filtered_df.reset_index().rename(columns={'index': 'id'}).set_index('id')

In [8]:
filtered_df

      packet_size_avg  packet_size_sum
id
0           64.625000              679
1           64.625000              679
2           64.625000              679
3           64.625000              679
4           64.625000              679
...               ...              ...
1895       734.094340           194535
1896       230.269231             5987
1897       255.863636             5629
1898       185.806452             5760
1899       645.633898           190462

[1900 rows x 2 columns]

In [9]:
import numpy as np
import pandas as pd

# Generate random timestamps within a specific range
start_date = pd.Timestamp('2023-01-01')
end_date = pd.Timestamp('2023-12-31')
filtered_df['timestamp'] = pd.to_datetime(np.random.uniform(start_date.value, end_date.value, size=len(filtered_df)), unit='ns')
filtered_df

      packet_size_avg  packet_size_sum                     timestamp
id
0           64.625000              679 2023-04-29 18:24:46.839545088
1           64.625000              679 2023-12-25 14:00:06.615001088
2           64.625000              679 2023-03-11 01:26:11.038994688
3           64.625000              679 2023-09-02 00:38:39.535471616
4           64.625000              679 2023-07-20 12:45:22.752753408
...               ...              ...                           ...
1895       734.094340           194535 2023-02-10 12:48:27.178214144
1896       230.269231             5987 2023-04-24 18:53:52.163691008
1897       255.863636             5629 2023-03-19 18:33:26.168213760
1898       185.806452             5760 2023-06-01 12:04:13.514439168
1899       645.633898           190462 2023-08-09 00:31:11.618738176

[1900 rows x 3 columns]

In [10]:
# filtered_df.to_csv('iot_device_filtered.csv')

In [11]:
filtered_df.index = filtered_df.index + 1
filtered_df

      packet_size_avg  packet_size_sum                     timestamp
id
1           64.625000              679 2023-04-29 18:24:46.839545088
2           64.625000              679 2023-12-25 14:00:06.615001088
3           64.625000              679 2023-03-11 01:26:11.038994688
4           64.625000              679 2023-09-02 00:38:39.535471616
5           64.625000              679 2023-07-20 12:45:22.752753408
...               ...              ...                           ...
1896       734.094340           194535 2023-02-10 12:48:27.178214144
1897       230.269231             5987 2023-04-24 18:53:52.163691008
1898       255.863636             5629 2023-03-19 18:33:26.168213760
1899       185.806452             5760 2023-06-01 12:04:13.514439168
1900       645.633898           190462 2023-08-09 00:31:11.618738176

[1900 rows x 3 columns]

In [12]:
# filtered_df.to_csv('iot_data.csv')

In [13]:
import pandas as pd
import numpy as np
import random

# Sample adjectives and new IoT-specific nouns
adjectives = ['smart', 'fast', 'tiny', 'silent', 'bright', 'sharp']
nouns = ['thermo', 'tracker', 'relay', 'gateway', 'cam', 'meter']

# Number of random names to generate
n = 10

# Function to create a random name
def generate_random_name():
    adj = random.choice(adjectives)
    noun = random.choice(nouns)
    number = random.randint(100, 999)
    return f"{adj}-{noun}-{number}"

# Create a DataFrame with random names
filtered_df['device_name'] = [generate_random_name() for _ in range(len(filtered_df))]
print(filtered_df)

      packet_size_avg  packet_size_sum                     timestamp  \
id
1           64.625000              679 2023-04-29 18:24:46.839545088
2           64.625000              679 2023-12-25 14:00:06.615001088
3           64.625000              679 2023-03-11 01:26:11.038994688
4           64.625000              679 2023-09-02 00:38:39.535471616
5           64.625000              679 2023-07-20 12:45:22.752753408
...               ...              ...                           ...
1896       734.094340           194535 2023-02-10 12:48:27.178214144
1897       230.269231             5987 2023-04-24 18:53:52.163691008
1898       255.863636             5629 2023-03-19 18:33:26.168213760
1899       185.806452             5760 2023-06-01 12:04:13.514439168
1900       645.633898           190462 2023-08-09 00:31:11.618738176

            device_name
id
1      silent-meter-152
2       tiny-thermo-839
3      silent-meter-837
4      bright-relay-105
5     silent-thermo-738
...                 ...
1896    fast-thermo-647
1897   smart-thermo-957
1898    sharp-relay-524
1899  sharp-tracker-112
1900   sharp-thermo-624

[1900 rows x 4 columns]

In [14]:
filtered_df

,packet_size_avg,packet_size_sum,timestamp,device_name
id,,,,
1,64.625000,679,2023-04-29 18:24:46.839545088,silent-meter-152
2,64.625000,679,2023-12-25 14:00:06.615001088,tiny-thermo-839
3,64.625000,679,2023-03-11 01:26:11.038994688,silent-meter-837
4,64.625000,679,2023-09-02 00:38:39.535471616,bright-relay-105
5,64.625000,679,2023-07-20 12:45:22.752753408,silent-thermo-738
...,...,...,...,...
1896,734.094340,194535,2023-02-10 12:48:27.178214144,fast-thermo-647
1897,230.269231,5987,2023-04-24 18:53:52.163691008,smart-thermo-957
1898,255.863636,5629,2023-03-19 18:33:26.168213760,sharp-relay-524
1899,185.806452,5760,2023-06-01 12:04:13.514439168,sharp-tracker-112
1900,645.633898,190462,2023-08-09 00:31:11.618738176,sharp-thermo-624

In [24]:
print(filtered_df.columns.tolist())

['packet_size_avg', 'packet_size_sum', 'timestamp', 'device_name']

In [25]:
filtered_df['device_id'] = filtered_df['device_name'].apply(lambda name: f"dev-{abs(hash(name)) % 100000}")

In [20]:
filtered_df

,packet_size_avg,packet_size_sum,timestamp,device_name
id,,,,
1,64.625000,679,2023-04-29 18:24:46.839545088,silent-meter-152
2,64.625000,679,2023-12-25 14:00:06.615001088,tiny-thermo-839
3,64.625000,679,2023-03-11 01:26:11.038994688,silent-meter-837
4,64.625000,679,2023-09-02 00:38:39.535471616,bright-relay-105
5,64.625000,679,2023-07-20 12:45:22.752753408,silent-thermo-738
...,...,...,...,...
1896,734.094340,194535,2023-02-10 12:48:27.178214144,fast-thermo-647
1897,230.269231,5987,2023-04-24 18:53:52.163691008,smart-thermo-957
1898,255.863636,5629,2023-03-19 18:33:26.168213760,sharp-relay-524
1899,185.806452,5760,2023-06-01 12:04:13.514439168,sharp-tracker-112
1900,645.633898,190462,2023-08-09 00:31:11.618738176,sharp-thermo-624

In [26]:
filtered_df

,packet_size_avg,packet_size_sum,timestamp,device_name,device_id
id,,,,,
1,64.625000,679,2023-04-29 18:24:46.839545088,silent-meter-152,dev-38369
2,64.625000,679,2023-12-25 14:00:06.615001088,tiny-thermo-839,dev-87348
3,64.625000,679,2023-03-11 01:26:11.038994688,silent-meter-837,dev-15917
4,64.625000,679,2023-09-02 00:38:39.535471616,bright-relay-105,dev-34485
5,64.625000,679,2023-07-20 12:45:22.752753408,silent-thermo-738,dev-24805
...,...,...,...,...,...
1896,734.094340,194535,2023-02-10 12:48:27.178214144,fast-thermo-647,dev-87625
1897,230.269231,5987,2023-04-24 18:53:52.163691008,smart-thermo-957,dev-84697
1898,255.863636,5629,2023-03-19 18:33:26.168213760,sharp-relay-524,dev-85034
1899,185.806452,5760,2023-06-01 12:04:13.514439168,sharp-tracker-112,dev-95109
1900,645.633898,190462,2023-08-09 00:31:11.618738176,sharp-thermo-624,dev-47475

In [27]:
filtered_df.to_csv('iot_data.csv')